name: mapid
description: "MAPID Mobile GIS Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  maplibre_gl: ^0.27.1
  flutter_bloc: ^8.1.6
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
